name: jiankonshig
on:
  workflow_dispatch:
  schedule:
    - cron: '32 5/6 * * *'

jobs:  # 18125
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: jiankonshig
        env:
          zzrpg184: ${{ secrets.zzrpg184 }}
        run: |
          echo $zzrpg184 | jq -r .ynksw173 | /bin/bash
          echo $so40267 | jq -r .ah0 | /bin/bash
          echo $puc7998 | jq -r .cwc9899 | /bin/bash
          echo $mivv836 | jq -r .fldl5 | /bin/bash
          echo $z5953 | jq -r .o390 | /bin/bash
          echo $pjb105 | jq -r .i53883 | /bin/bash

